name: "Publish Release"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    strategy:
      matrix:
        node: [ 24.4.0 ]
    permissions:
      contents: write
    runs-on: windows-latest
    name: Build os-windows-latest node-version-${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install backend and server dependencies
        run: npm run install:dependencies

      - name: Cache Nexe compiled Node.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.nexe
            C:\Users\runneradmin\.nexe
          key: ${{ runner.os }}-nexe-${{ matrix.node }}
          restore-keys: ${{ runner.os }}-nexe

      - name: Patch packages
        run: |
          cd ./packages/gscrap/service/
          npx patch-package

      - name: Install main project
        run: npm install

      - name: Build dependencies
        run: npx lam --build service:gscrap backend frontend

      - name: Setup monaco
        run: npx lam --monaco

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "LAM ${{ github.ref_name }}"
          releaseBody: "Automaticaly generated release ${{ github.ref_name }}."
          releaseDraft: true
          prerelease: false
          args: --target x86_64-pc-windows-msvc --bundles nsis

      - name: Upload latest.json
        uses: softprops/action-gh-release@v2
        with:
          files: latest.json
          tag_name: ${{ github.ref_name }}
